### ISSUE TITLE
New Event on Button hover or click

### ISSUE THREAD

**Issue by stollr** [ymc-thzi/clickspark.js#4]
One cool effect would be that the whole site rotates but only the target element keeps as it is, when the user hovers over it.

**Comment by ymc-thzi** [comment]
nice idea :+1: 
but I think that a particle emitting plugin should not do such crazy effects :-D you can add that easily to your click event for example like this

``` css
@keyframes rotate {
from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
body {
  animation: rotate 2s linear infinite;
}
```
